version: '3'

services:
  parking-recommendation-redis:
    container_name: parking-recommendation-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: eunhan97/parking-recommendation-redis
    ports:
      - "6379:6379"
    networks:
      - parking-recommendation-network

  parking-recommendation-database:
    container_name: parking-recommendation-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: eunhan97/parking-recommendation-database
    environment:
      - MARIADB_DATABASE=parking-recommendation
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - parking-recommendation-network

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - parking-recommendation-network

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - parking-recommendation-network

  parking-recommendation-app:
    container_name: parking-recommendation-app
    build:
      context: .
    environment:
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - parking-recommendation-database
      - parking-recommendation-redis
      - kafka
    networks:
      - parking-recommendation-network

networks:
  parking-recommendation-network:
    driver: bridge